/**
 * Per-item grocery emoji — longest keyword match on normalized name.
 * Offline, no network. Used by catalog bake + live list/search UI.
 */

import { normalizeGroceryText } from '@/lib/grocery/classify';

/** Longer / more specific phrases first. */
const RULES: Array<[string, string]> = [
  // Fruit
  ['honeycrisp', '🍎'],
  ['ambrosia', '🍎'],
  ['spartan', '🍎'],
  ['green apple', '🍏'],
  ['apple', '🍎'],
  ['banana', '🍌'],
  ['blueberry', '🫐'],
  ['blueberries', '🫐'],
  ['strawberry', '🍓'],
  ['strawberries', '🍓'],
  ['raspberry', '🍓'],
  ['raspberries', '🍓'],
  ['blackberry', '🫐'],
  ['grape', '🍇'],
  ['watermelon', '🍉'],
  ['cantaloupe', '🍈'],
  ['honeydew', '🍈'],
  ['pineapple', '🍍'],
  ['mango', '🥭'],
  ['peach', '🍑'],
  ['pear', '🍐'],
  ['cherry', '🍒'],
  ['cherries', '🍒'],
  ['kiwi', '🥝'],
  ['lemon', '🍋'],
  ['lime', '🍋'],
  ['orange', '🍊'],
  ['clementine', '🍊'],
  ['tangerine', '🍊'],
  ['grapefruit', '🍊'],
  ['apple juice', '🧃'],
  ['orange juice', '🧃'],
  ['tomato juice', '🧃'],
  ['avocado', '🥑'],
  ['coconut', '🥥'],
  ['tomato', '🍅'],
  ['olive', '🫒'],

  // Vegetables
  ['sweet potato', '🍠'],
  ['potato', '🥔'],
  ['carrot', '🥕'],
  ['broccoli', '🥦'],
  ['cauliflower', '🥦'],
  ['corn', '🌽'],
  ['cucumber', '🥒'],
  ['lettuce', '🥬'],
  ['romaine', '🥬'],
  ['spinach', '🥬'],
  ['kale', '🥬'],
  ['cabbage', '🥬'],
  ['pepper', '🫑'],
  ['chili', '🌶️'],
  ['garlic', '🧄'],
  ['onion', '🧅'],
  ['mushroom', '🍄'],
  ['eggplant', '🍆'],
  ['aubergine', '🍆'],
  ['zucchini', '🥒'],
  ['beans', '🫘'],
  ['chickpea', '🫘'],
  ['lentil', '🫘'],
  ['pea', '🟢'],
  ['celery', '🥬'],
  ['asparagus', '🥦'],
  ['herbs', '🌿'],
  ['basil', '🌿'],
  ['cilantro', '🌿'],
  ['parsley', '🌿'],
  ['mint', '🌿'],
  ['dill', '🌿'],
  ['thyme', '🌿'],
  ['rosemary', '🌿'],

  // Bakery
  ['bagel', '🥯'],
  ['croissant', '🥐'],
  ['pretzel', '🥨'],
  ['donut', '🍩'],
  ['doughnut', '🍩'],
  ['muffin', '🧁'],
  ['cupcake', '🧁'],
  ['cake', '🍰'],
  ['pie', '🥧'],
  ['tart', '🥧'],
  ['cookie', '🍪'],
  ['biscuit', '🍪'],
  ['bread', '🍞'],
  ['baguette', '🥖'],
  ['sourdough', '🍞'],
  ['bun', '🍞'],
  ['tortilla', '🫓'],
  ['pita', '🫓'],
  ['naan', '🫓'],
  ['waffle', '🧇'],
  ['pancake', '🥞'],

  // Dairy
  ['ice cream', '🍦'],
  ['gelato', '🍨'],
  ['popsicle', '🍧'],
  ['yogurt', '🥛'],
  ['yoghurt', '🥛'],
  ['yogourt', '🥛'],
  ['butter', '🧈'],
  ['margarine', '🧈'],
  ['cheese curd', '🧀'],
  ['cheddar', '🧀'],
  ['mozzarella', '🧀'],
  ['parmesan', '🧀'],
  ['brie', '🧀'],
  ['feta', '🧀'],
  ['cream cheese', '🧀'],
  ['cheese', '🧀'],
  ['egg', '🥚'],
  ['cream', '🥛'],
  ['half and half', '🥛'],
  ['milk', '🥛'],
  ['lait', '🥛'],

  // Meat / seafood
  ['bacon', '🥓'],
  ['ham', '🍖'],
  ['sausage', '🌭'],
  ['hot dog', '🌭'],
  ['hotdog', '🌭'],
  ['steak', '🥩'],
  ['beef', '🥩'],
  ['pork', '🥩'],
  ['lamb', '🥩'],
  ['veal', '🥩'],
  ['agneau', '🥩'],
  ['chicken wing', '🍗'],
  ['chicken', '🍗'],
  ['turkey', '🦃'],
  ['duck', '🦆'],
  ['shrimp', '🦐'],
  ['prawn', '🦐'],
  ['lobster', '🦞'],
  ['crab', '🦀'],
  ['oyster', '🦪'],
  ['salmon', '🐟'],
  ['tuna', '🐟'],
  ['cod', '🐟'],
  ['tilapia', '🐟'],
  ['fish', '🐟'],
  ['seafood', '🦐'],

  // Breakfast / pantry
  ['maple syrup', '🍁'],
  ['honey', '🍯'],
  ['peanut butter', '🥜'],
  ['almond butter', '🥜'],
  ['nutella', '🍫'],
  ['jam', '🫙'],
  ['jelly', '🫙'],
  ['cereal', '🥣'],
  ['oat', '🥣'],
  ['granola', '🥣'],
  ['porridge', '🥣'],
  ['shreddies', '🥣'],
  ['pasta', '🍝'],
  ['spaghetti', '🍝'],
  ['penne', '🍝'],
  ['macaroni', '🍝'],
  ['lasagna', '🍝'],
  ['noodle', '🍜'],
  ['ramen', '🍜'],
  ['rice', '🍚'],
  ['couscous', '🍚'],
  ['quinoa', '🍚'],
  ['flour', '🌾'],
  ['sugar', '🧂'],
  ['salt', '🧂'],
  ['pepper', '🧂'],
  ['spice', '🧂'],
  ['oil', '🫒'],
  ['vinegar', '🍾'],
  ['ketchup', '🍅'],
  ['mustard', '🟡'],
  ['mayonnaise', '🫙'],
  ['mayo', '🫙'],
  ['salsa', '🫙'],
  ['sauce', '🥫'],
  ['soup', '🍲'],
  ['broth', '🍲'],
  ['stock', '🍲'],
  ['beans canned', '🥫'],
  ['canned', '🥫'],

  // Snacks
  ['popcorn', '🍿'],
  ['chip', '🥔'],
  ['crisp', '🥔'],
  ['cracker', '🍘'],
  ['pretzel', '🥨'],
  ['nuts', '🥜'],
  ['almond', '🥜'],
  ['peanut', '🥜'],
  ['cashew', '🥜'],
  ['walnut', '🥜'],
  ['chocolate', '🍫'],
  ['candy', '🍬'],
  ['gummy', '🍬'],
  ['smarties', '🍬'],
  ['cookie', '🍪'],

  // Frozen / prepared
  ['pizza', '🍕'],
  ['fries', '🍟'],
  ['frites', '🍟'],
  ['poutine', '🍟'],
  ['burrito', '🌯'],
  ['taco', '🌮'],
  ['sushi', '🍣'],
  ['salad', '🥗'],
  ['sandwich', '🥪'],
  ['hamburger', '🍔'],
  ['burger', '🍔'],
  ['frozen', '🧊'],

  // Drinks
  ['coffee', '☕'],
  ['espresso', '☕'],
  ['tea', '🍵'],
  ['matcha', '🍵'],
  ['juice', '🧃'],
  ['smoothie', '🧋'],
  ['soda', '🥤'],
  ['cola', '🥤'],
  ['pop', '🥤'],
  ['ginger ale', '🧃'],
  ['lemonade', '🍋'],
  ['beer', '🍺'],
  ['wine', '🍷'],
  ['water', '💧'],
  ['sparkling', '🫧'],

  // Baby / pet / household / personal
  ['diaper', '🧷'],
  ['wipe', '🧻'],
  ['formula', '🍼'],
  ['baby food', '🍼'],
  ['dog', '🐶'],
  ['cat', '🐱'],
  ['litter', '🐱'],
  ['pet', '🐾'],
  ['shampoo', '🧴'],
  ['conditioner', '🧴'],
  ['toothpaste', '🪥'],
  ['toothbrush', '🪥'],
  ['deodorant', '🧴'],
  ['soap', '🧼'],
  ['lotion', '🧴'],
  ['razor', '🪒'],
  ['advil', '💊'],
  ['tylenol', '💊'],
  ['vitamin', '💊'],
  ['bandage', '🩹'],
  ['detergent', '🫧'],
  ['bleach', '🧪'],
  ['cleaner', '🧹'],
  ['laundry', '🫧'],
  ['toilet paper', '🧻'],
  ['paper towel', '🧻'],
  ['tissue', '🤧'],
  ['foil', '📦'],
  ['saran', '📦'],
  ['plastic wrap', '📦'],
  ['wrap', '📦'],
  ['garbage', '🗑️'],
  ['trash', '🗑️'],
];

// Sort once by keyword length desc for longest-match-wins
const SORTED = [...RULES].sort((a, b) => b[0].length - a[0].length || a[0].localeCompare(b[0]));

const AISLE_FALLBACK: Record<string, string> = {
  produce: '🥬',
  bakery: '🍞',
  deli: '🥪',
  meat_seafood: '🥩',
  dairy_eggs: '🥛',
  breakfast: '🥣',
  pantry: '🫙',
  canned: '🥫',
  snacks: '🍿',
  frozen: '🧊',
  beverages: '🧃',
  baby_kids: '🍼',
  household: '🧹',
  personal_care: '🧴',
  pet: '🐾',
  other: '🛒',
};

/**
 * Best-effort emoji for a grocery name.
 * Prefer specific food match; else aisle; else cart.
 */
export function emojiForGroceryItem(
  name: string,
  categoryId?: string | null
): string {
  const n = normalizeGroceryText(name);
  if (!n) return AISLE_FALLBACK[categoryId ?? ''] ?? '🛒';

  for (const [keyword, emoji] of SORTED) {
    if (n.includes(keyword)) return emoji;
  }
  if (categoryId && AISLE_FALLBACK[categoryId]) return AISLE_FALLBACK[categoryId];
  return '🛒';
}

/** Enrich a catalog product icon (recompute from name). */
export function resolveProductIcon(
  name: string,
  categoryId?: string | null,
  existing?: string | null
): string {
  const matched = emojiForGroceryItem(name, categoryId);
  // Prefer specific match over generic aisle/browse icons
  const generic = new Set([
    ...Object.values(AISLE_FALLBACK),
    '🍎',
    '🥕',
    '🌿',
    '🥐',
    '🥗',
    '🍗',
    '🐟',
    '🫙',
    '🧂',
    '🍲',
    '🍦',
    '☕',
    '🛒',
  ]);
  if (!existing || generic.has(existing)) return matched;
  // Keep curated staple icons when they already look specific
  return existing;
}
