/**
 * Recorded GPT conversational lines for the How it works demo.
 *
 * Generated by scripts/bake-how-it-works-via-edge.mjs (gpt-4o-mini-tts via staging).
 * Do not fall back to device Speech for this demo — the whole point is human-sounding chat.
 */

const RECORDINGS: Record<string, number> = {
  'task-ask': require('@/assets/how-it-works/task-ask.m4a'),
  'task-fill-1': require('@/assets/how-it-works/task-fill-1.m4a'),
  'task-fill-2': require('@/assets/how-it-works/task-fill-2.m4a'),
  'task-done': require('@/assets/how-it-works/task-done.m4a'),
  'grocery-ask': require('@/assets/how-it-works/grocery-ask.m4a'),
  'grocery-1': require('@/assets/how-it-works/grocery-1.m4a'),
  'grocery-2': require('@/assets/how-it-works/grocery-2.m4a'),
  'grocery-done': require('@/assets/how-it-works/grocery-done.m4a'),
  'calendar-ask': require('@/assets/how-it-works/calendar-ask.m4a'),
  'calendar-1': require('@/assets/how-it-works/calendar-1.m4a'),
  'calendar-2': require('@/assets/how-it-works/calendar-2.m4a'),
  'calendar-3': require('@/assets/how-it-works/calendar-3.m4a'),
  'calendar-done': require('@/assets/how-it-works/calendar-done.m4a'),
  'trip-ask': require('@/assets/how-it-works/trip-ask.m4a'),
  'trip-1': require('@/assets/how-it-works/trip-1.m4a'),
  'trip-2': require('@/assets/how-it-works/trip-2.m4a'),
  'trip-3': require('@/assets/how-it-works/trip-3.m4a'),
  'trip-done': require('@/assets/how-it-works/trip-done.m4a'),
};

/** True once any line has been recorded — the player picks its path from this. */
export function hasRecordedDemoAudio(): boolean {
  return Object.keys(RECORDINGS).length > 0;
}

/** The recording for a beat, or null when that line has no clip yet. */
export function recordedDemoAudio(beatId: string): number | null {
  return RECORDINGS[beatId] ?? null;
}

/** Which beats are still missing a recording — used by tests when wiring audio. */
export function missingDemoRecordings(beatIds: string[]): string[] {
  if (!hasRecordedDemoAudio()) return beatIds;
  return beatIds.filter((id) => RECORDINGS[id] == null);
}
